cloudposse-examples/atmos-pro-example-advanced

- .github/workflows/atmos-preview.yaml
- .github/workflows/atmos-release.yaml
- .github/workflows/atmos-terraform-apply.yaml
- .github/workflows/atmos-terraform-plan.yaml
- .github/workflows/labeler.yaml
- .github/workflows/labeler.yml
- .github/workflows/validate.yml
- components/terraform/account-map/README.md
- components/terraform/account-map/modules/iam-roles/main.tf
- components/terraform/account-map/modules/iam-roles/providers.tf
- components/terraform/account-map/modules/team-assume-role-policy/README.md
- components/terraform/account-map/modules/team-assume-role-policy/context.tf
- components/terraform/account-map/modules/team-assume-role-policy/github-assume-role-policy.mixin.tf
- components/terraform/account-map/modules/team-assume-role-policy/main.tf
- components/terraform/account-map/modules/team-assume-role-policy/versions.tf
- components/terraform/github-oidc-provider/README.md
- components/terraform/github-oidc-provider/outputs.tf
- components/terraform/github-oidc-provider/versions.tf
- stacks/catalog/github-oidc-provider.yaml
- stacks/catalog/github-oidc-role/defaults.yaml
- stacks/orgs/ex1/core/auto/global-region/demo.yaml
- stacks/orgs/ex1/plat/dev/us-east-2/demo.yaml
- stacks/orgs/ex1/plat/prod/us-east-2/demo.yaml
- stacks/orgs/ex1/plat/staging/us-east-2/demo.yaml
- Adding mock s3 bucket components
- Creating GitHub Action workflows for triggering atmos on dispatch
- Test components
- Integrate with Atmos Pro application
- customer engagement
> Atmos GitOps Workflows with Mock Components

- .github/workflows/atmos-preview.yaml
- components/docker/infrastructure/Dockerfile
- rootfs/usr/local/etc/atmos/atmos.yaml
- stacks/orgs/ex1/plat/dev/us-east-2/demo.yaml
- Add superficial change to s3 bucket component
- Validate describe affected trigger workflow
- n/a
> Validate Describe Affected

- .github/auto-release.yml
- .github/workflows/auto-release.yml
- Add auto-release configuration
- Create draft release on merges into main
- n/a
> Release Drafter

- .github/workflows/auto-release.yml
- Add draft release job to auto-release workflow
- Draft release on merges into main
- n/a
> Corrected Release Drafter

- .github/workflows/atmos-terraform-apply.yaml
- .github/workflows/atmos-terraform-plan.yaml
- components/terraform/account-map/modules/iam-roles/main.tf
- components/terraform/account-map/outputs.tf
- Completing the Terraform Plan Dispatch workflow
- Plan terraform on demand
- customer engagement
> Plan Dispatch Workflow

- .github/actions/retrieve-plan/action.yaml
- .github/workflows/atmos-terraform-apply.yaml
- .github/workflows/atmos-terraform-plan.yaml
- Completing the Atmos Terraform Apply Workflow
- Apply terraform on demand. Either pull or create Terraform Plan
- customer engagement
> Terraform Apply Workflows

- .github/workflows/atmos-preview.yaml
- .github/workflows/atmos-release.yaml
- .github/workflows/atmos-terraform-apply.yaml
- .github/workflows/atmos-terraform-plan.yaml
- Replaced echo with curl to trigger atmos pro test endpoint
- Updated concurrency settings for running per stack/component
- Misc improvements and feedback from office hours
- Feedback cycle 1
- n/a
> Feat: Test Atmos Pro Endpoint and Concurrency

- stacks/orgs/ex1/plat/dev/us-east-2/demo.yaml
> make simple change

- stacks/orgs/ex1/plat/dev/us-east-2/demo.yaml
- Update parent name to parent4 in demo.yaml
- Test changes
- n/a
> Test Changes

- .github/workflows/atmos-release.yaml
- stacks/orgs/ex1/plat/dev/us-east-2/demo.yaml
- Checkout before getting release
- Debug release get affected
- n/a
> Fix Release Workflow

- .github/workflows/atmos-preview.yaml
- .github/workflows/atmos-release.yaml
- stacks/orgs/ex1/plat/dev/us-east-2/demo.yaml
- Update Atmos workflows to use correct commit SHA
- Copy API call from preview workflow
- Trigger atmos pro via release
- n/a
> Corrected Release Atmos Pro API Call

- .github/workflows/atmos-terraform-apply.yaml
- Changed the Terraform Apply workflow to set `run-name: apply ${{ inputs.component }}/${{ inputs.stack }}/${{ inputs.atmos_pro_run_id}}`
- Changed `plan` to `apply`
- n/a
> Corrected Apply `run-name`

- stacks/orgs/ex1/plat/dev/us-east-2/demo.yaml
- This is a demo
- Provide the justifications for the changes (e.g. business case).
- Describe why these changes were made (e.g. why do these commits fix the problem?)
- Use bullet points to be concise and to the point.
- Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow).
- Use `closes #123`, if this PR closes a GitHub issue `#123`
- Use `closes JIRA-123`, if this PR closes a Jira Issue `JIRA-123` where `JIRA` is the project abbreviation.
> demo change

- stacks/orgs/ex1/plat/dev/us-east-2/demo.yaml
Demo!
- Provide the justifications for the changes (e.g. business case).
- Describe why these changes were made (e.g. why do these commits fix the problem?)
- Use bullet points to be concise and to the point.
- Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow).
- Use `closes #123`, if this PR closes a GitHub issue `#123`
- Use `closes JIRA-123`, if this PR closes a Jira Issue `JIRA-123` where `JIRA` is the project abbreviation.
> demo change 10

- stacks/orgs/ex1/plat/dev/us-east-2/demo.yaml
- Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
- Use bullet points to be concise and to the point.
- Provide the justifications for the changes (e.g. business case).
- Describe why these changes were made (e.g. why do these commits fix the problem?)
- Use bullet points to be concise and to the point.
- Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow).
- Use `closes #123`, if this PR closes a GitHub issue `#123`
- Use `closes JIRA-123`, if this PR closes a Jira Issue `JIRA-123` where `JIRA` is the project abbreviation.
> another demo

- components/terraform/cluster/context.tf
- components/terraform/cluster/main.tf
- components/terraform/cluster/versions.tf
- components/terraform/load-balancer/context.tf
- components/terraform/load-balancer/main.tf
- components/terraform/load-balancer/versions.tf
- components/terraform/network/context.tf
- components/terraform/network/main.tf
- components/terraform/network/versions.tf
- stacks/catalog/cluster.yaml
- stacks/catalog/load-balancer.yaml
- stacks/catalog/network.yaml
- stacks/orgs/ex1/plat/dev/us-east-2/demo.yaml
- stacks/orgs/ex1/plat/prod/us-east-2/demo.yaml
- stacks/orgs/ex1/plat/staging/us-east-2/demo.yaml
- Added mock `network`, `load-balancer`, and `cluster` components
- Faster demo, better illustrate deps
> Mock Components

- stacks/catalog/object-storage.yaml
> testing 12

- stacks/catalog/object-storage.yaml
> testing 13

- stacks/catalog/object-storage.yaml
> testing 14

- stacks/catalog/object-storage.yaml
> testing 15

- stacks/mixins/atmos-pro/default.yaml
> testing 16

- stacks/mixins/atmos-pro/default.yaml
> testing 17

- stacks/catalog/object-storage.yaml
> testing 19

- stacks/catalog/object-storage.yaml
> Testing 20

- stacks/catalog/object-storage.yaml
> testing 21

- stacks/catalog/object-storage.yaml
> Testing 22

- stacks/catalog/object-storage.yaml
> testing 23

- .github/workflows/atmos-preview.yaml
- .github/workflows/atmos-release.yaml
- Update workflows to use the production app
- Update the API key secret to be a production key
- We have launched the production application
> update workflows for production

- stacks/mixins/atmos-pro/default.yaml
- Update atmos pro settings to use maps instead of lists
- So that the settings section can be fully deep merged
> DEV-2463 update atmos pro settings

- .github/README.md
- README.yaml
- Return deps mapping mermaid diagram in the README
- Provide visual aid to component examples
- Unintentionally removed by #106
> Bring Back Mermaid

- atmos.yaml
enable templates for atmos
we need these to process the apply environment
.
> Enabled templates
